name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.continue-on-error || false }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        deno-version: [v2.x]
        include:
          - os: ubuntu-latest
            deno-version: canary
            continue-on-error: true
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
          cache: true
      - name: deno ci
        run: deno ci
      - name: Run tests across workspace
        run: deno test --allow-net --allow-write --allow-read --allow-env --allow-run
